
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v3.5  Build: December 11th, 2012
-- SQL Server 2000/2005/2008/2008R2/2012/Express DDL Script generated from project: Enio
-- Project filename: G:\Documents\Visual Studio 2010\Projects\NinjaSoftware.Enio\Enio.llblgenproj
-- Script generated on: 24-sij-2013 17:05.01
--
-- This is an Update script for updating an existing data model to a newer version. If you want DDL SQL for a new model,
-- please create a Create script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime.
--
-- Please run the scripts in the right order, use the timestamp in the filename and inside this script for that.
-- This script might need adjustment in some statements. You should consider this script as a starting point for
-- upgrading the existing data model.
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- Drop constraints referring to elements which are changed in this script (constraints are recreated later on)
-- ###############################################################################################################

USE [Enio]
GO

-- ###############################################################################################################
-- Rename statements
-- ###############################################################################################################

USE [Enio]
GO

-- ###############################################################################################################
-- DROP statements for elements no longer needed or replaced elements.
-- ###############################################################################################################

USE [Enio]
GO

ALTER TABLE [dbo].[Config] DROP CONSTRAINT [PK_bb95011426dab7a6af2f7ecc673]
GO

-- ###############################################################################################################
-- ADD statements for new elements (except FK/UC)
-- ###############################################################################################################

USE [Enio]
GO

ALTER TABLE [dbo].[Config] 
	ADD [ConfigId] [bigint] NOT NULL
GO

-- ###############################################################################################################
-- ALTER statements for table fields and ADD statements for new primary key constraints
-- ###############################################################################################################

USE [Enio]
GO

ALTER TABLE [dbo].[Config] WITH NOCHECK 
	ADD CONSTRAINT [PK_9db7dd14657bbe5f770fb125382] PRIMARY KEY CLUSTERED 
	( 
		[ConfigId] 
	) ON [PRIMARY]
GO

-- ###############################################################################################################
-- ADD statements for new foreign key constraints and unique constraints
-- ###############################################################################################################

USE [Enio]
GO

