
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v3.5  Build: December 11th, 2012
-- SQL Server 2000/2005/2008/2008R2/2012/Express DDL Script generated from project: Enio
-- Project filename: G:\Documents\Visual Studio 2010\Projects\NinjaSoftware.Enio\Enio.llblgenproj
-- Script generated on: 25-sij-2013 10:45.14
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 

USE [Enio]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP Foreign keys
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Artikl] DROP CONSTRAINT [FK_e4bada6438fa868f9887823d288]
GO

ALTER TABLE [dbo].[AuditInfo] DROP CONSTRAINT [FK_71d8b1d4d6797630ede27dc9b3e]
GO

ALTER TABLE [dbo].[AuditInfo] DROP CONSTRAINT [FK_ace455b44559f9ed0ca5ec3cabe]
GO

ALTER TABLE [dbo].[AuditInfo] DROP CONSTRAINT [FK_b683b7b46a8bfb4f52d2b6dda84]
GO

ALTER TABLE [dbo].[Cjenik] DROP CONSTRAINT [FK_30a409b4f3ca8d0bdd26e4b96e0]
GO

ALTER TABLE [dbo].[Cjenik] DROP CONSTRAINT [FK_47a832d412683069e687ef0f2f7]
GO

ALTER TABLE [dbo].[Error] DROP CONSTRAINT [FK_a100a724e408ba3ba5fc21d3565]
GO

ALTER TABLE [dbo].[RacunGlava] DROP CONSTRAINT [FK_63db5294b5799fd45e2e934efef]
GO

ALTER TABLE [dbo].[RacunGlava] DROP CONSTRAINT [FK_b3f3866433f9629df549bb2ba25]
GO

ALTER TABLE [dbo].[RacunGlava] DROP CONSTRAINT [FK_e2b0d6c4ba78d54a196f1b6c476]
GO

ALTER TABLE [dbo].[RacunStavka] DROP CONSTRAINT [FK_669f8ee405cbffd0c838cda7063]
GO

ALTER TABLE [dbo].[RacunStavka] DROP CONSTRAINT [FK_ae23b95474ca1ed12a5178b760e]
GO

ALTER TABLE [dbo].[User] DROP CONSTRAINT [FK_dfb14634469b1397878150e222d]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'dbo' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE [dbo].[Artikl]
GO

DROP TABLE [dbo].[AuditInfo]
GO

DROP TABLE [dbo].[AuditInfoActionTypeRo]
GO

DROP TABLE [dbo].[Brojac]
GO

DROP TABLE [dbo].[Cjenik]
GO

DROP TABLE [dbo].[Config]
GO

DROP TABLE [dbo].[EntityRo]
GO

DROP TABLE [dbo].[Error]
GO

DROP TABLE [dbo].[Partner]
GO

DROP TABLE [dbo].[Pdv]
GO

DROP TABLE [dbo].[RacunGlava]
GO

DROP TABLE [dbo].[RacunStavka]
GO

DROP TABLE [dbo].[RoleRo]
GO

DROP TABLE [dbo].[StatusRo]
GO

DROP TABLE [dbo].[Tarifa]
GO

DROP TABLE [dbo].[User]
GO
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Enio'
-- ----------------------------------------------------------------------------------------------------------------

USE master
GO
CREATE DATABASE [Enio] /* ON PRIMARY (NAME=Enio_dat, FILENAME='c:\mycatalogs\Enio.mdf', SIZE=10MB) */
GO


USE [Enio]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[Artikl] 
(
	[ArtiklId] [bigint] IDENTITY (1,1) NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Jm] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[StatusId] [bigint] NOT NULL, 
	[PdvId] [bigint] NOT NULL, 
	[IsActive] [bit] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[AuditInfo] 
(
	[ActionDateTime] [datetime] NOT NULL, 
	[AuditInfoActionTypeId] [bigint] NOT NULL, 
	[AuditInfoId] [bigint] IDENTITY (1,1) NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[EntityId] [bigint] NOT NULL, 
	[JsonData] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[PrimaryKeyValue] [bigint] NOT NULL, 
	[UserId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[AuditInfoActionTypeRo] 
(
	[AuditInfoActionTypeId] [bigint] NOT NULL, 
	[Code] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Name] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Brojac] 
(
	[BrojacId] [bigint] IDENTITY (1,1) NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Godina] [smallint] NOT NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[SlijedeciBroj] [int] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Cjenik] 
(
	[ArtiklId] [bigint] NOT NULL, 
	[Cijena] [decimal] (10, 4) NOT NULL, 
	[CjenikId] [bigint] IDENTITY (1,1) NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[PartnerId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Config] 
(
	[Adresa] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[AktivnaGodina] [smallint] NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Mjesto] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Oib] [nvarchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Zr] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[ConfigId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[EntityRo] 
(
	[Code] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[EntityId] [bigint] NOT NULL, 
	[Name] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Error] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[ErrorDateTime] [datetime] NOT NULL, 
	[ErrorId] [bigint] IDENTITY (1,1) NOT NULL, 
	[Message] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[ParentErrorId] [bigint] NULL, 
	[StackTrace] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Partner] 
(
	[Adresa] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Mjesto] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Oib] [nvarchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[PartnerId] [bigint] IDENTITY (1,1) NOT NULL, 
	[Posta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Valuta] [smallint] NOT NULL, 
	[IsActive] [bit] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Pdv] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Naziv] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[PdvId] [bigint] IDENTITY (1,1) NOT NULL, 
	[Stopa] [decimal] (4, 2) NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RacunGlava] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Datum] [datetime] NOT NULL, 
	[Godina] [smallint] NOT NULL, 
	[MjestoRadaAdresa] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[MjestoRadaNaziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[PartnerId] [bigint] NOT NULL, 
	[RacunGlavaId] [bigint] IDENTITY (1,1) NOT NULL, 
	[StatusId] [bigint] NOT NULL, 
	[TarifaId] [bigint] NOT NULL, 
	[TarifaStopa] [decimal] (5, 2) NOT NULL, 
	[Valuta] [smallint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RacunStavka] 
(
	[ArtiklId] [bigint] NOT NULL, 
	[Cijena] [decimal] (10, 2) NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Iznos] [decimal] (10, 2) NOT NULL, 
	[Kolicina] [decimal] (8, 2) NOT NULL, 
	[PdvIznos] [decimal] (10, 2) NOT NULL, 
	[PdvPosto] [decimal] (4, 2) NOT NULL, 
	[Pozicija] [smallint] NOT NULL, 
	[RacunGlavaId] [bigint] NOT NULL, 
	[RacunStavkaId] [bigint] IDENTITY (1,1) NOT NULL, 
	[TarifaIznos] [decimal] (10, 2) NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RoleRo] 
(
	[Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[RoleId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[StatusRo] 
(
	[Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[StatusId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Tarifa] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Stopa] [decimal] (5, 2) NOT NULL, 
	[TarifaId] [bigint] IDENTITY (1,1) NOT NULL, 
	[IsActive] [bit] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[User] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[UserId] [bigint] IDENTITY (1,1) NOT NULL, 
	[Password] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Username] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[RoleId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints and Unique constraints
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Enio'
-- ----------------------------------------------------------------------------------------------------------------

USE [Enio]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Artikl] WITH NOCHECK 
	ADD CONSTRAINT [PK_d480edb42f7b917ecc486c70076] PRIMARY KEY CLUSTERED 
	( 
		[ArtiklId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AuditInfo] WITH NOCHECK 
	ADD CONSTRAINT [PK_58b99964a5998f98514f164efe9] PRIMARY KEY CLUSTERED 
	( 
		[AuditInfoId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AuditInfoActionTypeRo] WITH NOCHECK 
	ADD CONSTRAINT [PK_b2d1cb942f0960b4c986e999301] PRIMARY KEY CLUSTERED 
	( 
		[AuditInfoActionTypeId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Brojac] WITH NOCHECK 
	ADD CONSTRAINT [PK_15c6f4d4f51b2c99c458e66c8c3] PRIMARY KEY CLUSTERED 
	( 
		[BrojacId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Cjenik] WITH NOCHECK 
	ADD CONSTRAINT [PK_115005a482f8b1a2a795c97ea20] PRIMARY KEY CLUSTERED 
	( 
		[CjenikId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Config] WITH NOCHECK 
	ADD CONSTRAINT [PK_9db7dd14657bbe5f770fb125382] PRIMARY KEY CLUSTERED 
	( 
		[ConfigId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EntityRo] WITH NOCHECK 
	ADD CONSTRAINT [PK_eb1b8164a0ea94dfeb697be7adc] PRIMARY KEY CLUSTERED 
	( 
		[EntityId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Error] WITH NOCHECK 
	ADD CONSTRAINT [PK_1f36bf8439b98a3f181de1b803d] PRIMARY KEY CLUSTERED 
	( 
		[ErrorId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Partner] WITH NOCHECK 
	ADD CONSTRAINT [PK_671b0fd4b46b4662786ad978f9a] PRIMARY KEY CLUSTERED 
	( 
		[PartnerId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Pdv] WITH NOCHECK 
	ADD CONSTRAINT [PK_6ce26124826be268a53e8a611a8] PRIMARY KEY CLUSTERED 
	( 
		[PdvId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RacunGlava] WITH NOCHECK 
	ADD CONSTRAINT [PK_ec513c84e8aa0b477cb3ce2816d] PRIMARY KEY CLUSTERED 
	( 
		[RacunGlavaId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RacunStavka] WITH NOCHECK 
	ADD CONSTRAINT [PK_03c1f0c4af58c17ce285c941812] PRIMARY KEY CLUSTERED 
	( 
		[RacunStavkaId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RoleRo] WITH NOCHECK 
	ADD CONSTRAINT [PK_52296334a7aa55d86c550e11b3b] PRIMARY KEY CLUSTERED 
	( 
		[RoleId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[StatusRo] WITH NOCHECK 
	ADD CONSTRAINT [PK_7a613b94012823b5843f2fed461] PRIMARY KEY CLUSTERED 
	( 
		[StatusId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Tarifa] WITH NOCHECK 
	ADD CONSTRAINT [PK_b4c9f554a22baee23e425894791] PRIMARY KEY CLUSTERED 
	( 
		[TarifaId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[User] WITH NOCHECK 
	ADD CONSTRAINT [PK_65be2654831a0f712588a778c90] PRIMARY KEY CLUSTERED 
	( 
		[UserId] 
	) ON [PRIMARY]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Cjenik] 
	ADD CONSTRAINT [UC_e54ae784860b5b0411d030fdd1b] UNIQUE NONCLUSTERED
	(
		[ArtiklId], [PartnerId] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- All foreign Key constraints
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Artikl] 
	ADD CONSTRAINT [FK_e4bada6438fa868f9887823d288] FOREIGN KEY
	(
		[PdvId] 
	)
	REFERENCES [dbo].[Pdv]
	(
		[PdvId] 
	)
GO

ALTER TABLE [dbo].[AuditInfo] 
	ADD CONSTRAINT [FK_71d8b1d4d6797630ede27dc9b3e] FOREIGN KEY
	(
		[AuditInfoActionTypeId] 
	)
	REFERENCES [dbo].[AuditInfoActionTypeRo]
	(
		[AuditInfoActionTypeId] 
	)
GO

ALTER TABLE [dbo].[AuditInfo] 
	ADD CONSTRAINT [FK_ace455b44559f9ed0ca5ec3cabe] FOREIGN KEY
	(
		[EntityId] 
	)
	REFERENCES [dbo].[EntityRo]
	(
		[EntityId] 
	)
GO

ALTER TABLE [dbo].[AuditInfo] 
	ADD CONSTRAINT [FK_b683b7b46a8bfb4f52d2b6dda84] FOREIGN KEY
	(
		[UserId] 
	)
	REFERENCES [dbo].[User]
	(
		[UserId] 
	)
GO

ALTER TABLE [dbo].[Cjenik] 
	ADD CONSTRAINT [FK_30a409b4f3ca8d0bdd26e4b96e0] FOREIGN KEY
	(
		[ArtiklId] 
	)
	REFERENCES [dbo].[Artikl]
	(
		[ArtiklId] 
	)
GO

ALTER TABLE [dbo].[Cjenik] 
	ADD CONSTRAINT [FK_47a832d412683069e687ef0f2f7] FOREIGN KEY
	(
		[PartnerId] 
	)
	REFERENCES [dbo].[Partner]
	(
		[PartnerId] 
	)
GO

ALTER TABLE [dbo].[Error] 
	ADD CONSTRAINT [FK_a100a724e408ba3ba5fc21d3565] FOREIGN KEY
	(
		[ParentErrorId] 
	)
	REFERENCES [dbo].[Error]
	(
		[ErrorId] 
	)
GO

ALTER TABLE [dbo].[RacunGlava] 
	ADD CONSTRAINT [FK_63db5294b5799fd45e2e934efef] FOREIGN KEY
	(
		[PartnerId] 
	)
	REFERENCES [dbo].[Partner]
	(
		[PartnerId] 
	)
GO

ALTER TABLE [dbo].[RacunGlava] 
	ADD CONSTRAINT [FK_b3f3866433f9629df549bb2ba25] FOREIGN KEY
	(
		[StatusId] 
	)
	REFERENCES [dbo].[StatusRo]
	(
		[StatusId] 
	)
GO

ALTER TABLE [dbo].[RacunGlava] 
	ADD CONSTRAINT [FK_e2b0d6c4ba78d54a196f1b6c476] FOREIGN KEY
	(
		[TarifaId] 
	)
	REFERENCES [dbo].[Tarifa]
	(
		[TarifaId] 
	)
GO

ALTER TABLE [dbo].[RacunStavka] 
	ADD CONSTRAINT [FK_669f8ee405cbffd0c838cda7063] FOREIGN KEY
	(
		[RacunGlavaId] 
	)
	REFERENCES [dbo].[RacunGlava]
	(
		[RacunGlavaId] 
	)
GO

ALTER TABLE [dbo].[RacunStavka] 
	ADD CONSTRAINT [FK_ae23b95474ca1ed12a5178b760e] FOREIGN KEY
	(
		[ArtiklId] 
	)
	REFERENCES [dbo].[Artikl]
	(
		[ArtiklId] 
	)
GO

ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [FK_dfb14634469b1397878150e222d] FOREIGN KEY
	(
		[RoleId] 
	)
	REFERENCES [dbo].[RoleRo]
	(
		[RoleId] 
	)
GO
